### ISSUE TITLE
Realizar el diagrama entidad-relacion del proyecto formativo

### ISSUE THREAD

**Issue by SantiagoIglesia** [CarsOk/droguerias_darcy#8]
## Cards
**Como:** Aprendiz SENA
**Quiero:** Realizar el diagrama entidad-relacion
**Para:** Estar al día con la documentación del proyecto formativo y tener claro los aspectos fundamentales de este

## Criterios de aceptación 
- [x] Detallar los aspectos importantes
- [x] Ningún error ortografico con las variables y los tipos
- [x] Tener una estructura de manera Logica

### **Puntos de Dificultad:** 10

**Comment by JabesGod** [comment]
[uml.proyecto.zip](https://github.com/CarsOk/droguerias_darcy/files/8846329/uml.proyecto.zip)
